version: 2.1
commands:
  copy-markdown:
    parameters:
      destination:
        description: destination directory
        type: string
        default: docs
jobs:
  parameter_test:
    steps:
      - run: echo  << parameters.destination >>
workflows:
  version: 2
  build-test-adhoc:
    jobs:
      parameter_test
    
