version: 2.1

executors:
  node-docker: # declares a reusable executor
    docker:
      - image: cimg/node

jobs:
  test1:
    parameters:
      lane:
        description: "LANE"
        default: "test"
        type: string
    executor:
      name: node-docker
      version: <<parameters.lane>>
    steps:
      - checkout
      - run: echo <<parameters.lane>>
      
workflows:
  matrix-tests:
    jobs:
      - test1
#           matrix:
#             parameters:
#               lane:
#                 - test
