version: 2.1

parameters:
  pull_request:
    type: boolean
    default: false

orbs:
  welcome: circleci/welcome-orb@0.4.1
  hello: circleci/hello-build@0.0.5

workflows:
  push:
    unless: << pipeline.parameters.pull_request >>
    jobs:
      - welcome/run

  pull_request:
    when: << pipeline.parameters.pull_request >>
    jobs:
      - hello/hello-build
