version: 2.1

commands:
  list-files:
    parameters:
      os:
        type: enum
        default: "windows" #invalid declaration of default that does not appear in the comma-separated enum list
        enum: ["darwin", "linux"]

jobs:
  parameter_test:
    steps:
      - run: echo  << parameters.os >>
workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - parameter_test
    
