version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            apt update
            apt install curl
            curl http://some.url --output some.file
