version: 2.1

commands:
  list-files:
    parameters:
      os:
        default: "linux"
        description: The target Operating System for the heroku binary. Must be one of "linux", "darwin", "win32".
        type: enum
        enum: ["linux", "darwin", "win32"]

jobs:
  test:
    steps:
      - run: echo  << pipeline.parameters.os >>
  
workflows:
  my-workflow:
    jobs:
      - test
