version: 2.1

parameters:
  pull_request:
    type: boolean
    default: false
orbs:
    hello: circleci/hello-build@0.0.5
workflows:
    "Hello Workflow":
        jobs:
          - hello/hello-build
