version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/ruby:3.0.3-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

commands:
  list-files:
    parameters:
      os:
        default: "linux"
        description: The target Operating System for the heroku binary. Must be one of "linux", "darwin", "win32".
        type: enum
        enum: ["linux", "darwin", "win32"]
    steps:
      - run: echo  << parameters.os >>

jobs:
  my-job:
    executor: my-executor
    steps:
      - run: echo < parameters.os >>
 
workflows:
  my-workflow:
    jobs:
      - my-job
